-- MySQL Script generated by MySQL Workbench
-- lun 17 dic 2018 17:19:30 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gameCenter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gameCenter` ;

-- -----------------------------------------------------
-- Schema gameCenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gameCenter` DEFAULT CHARACTER SET utf8 ;
USE `gameCenter` ;

-- -----------------------------------------------------
-- Table `gameCenter`.`Genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`Genero` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`Genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(64) NOT NULL COMMENT 'Nombre del genero',
  `Descripcion` VARCHAR(64) NOT NULL COMMENT 'Descripción del contenido del genero',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Generos de videojuegos';


-- -----------------------------------------------------
-- Table `gameCenter`.`CalificacionEdad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`CalificacionEdad` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`CalificacionEdad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(32) NOT NULL COMMENT 'Nombre de la calificación',
  `Imagen` VARCHAR(64) NOT NULL COMMENT 'Imagen de la calificación\n',
  `Descripcion` VARCHAR(128) NOT NULL COMMENT 'Descripción de la calificación\n',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) )
ENGINE = InnoDB
COMMENT = 'Posibles calificaciones de PEGI obtenidas por los juegos para las distintas edades';


-- -----------------------------------------------------
-- Table `gameCenter`.`Productora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`Productora` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`Productora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(64) NOT NULL COMMENT 'Nombre de la plataforma',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) )
ENGINE = InnoDB
COMMENT = 'Conjunto de productoras en las que se pueden sacar los juegos\n';


-- -----------------------------------------------------
-- Table `gameCenter`.`Juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`Juego` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`Juego` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador unico del juego',
  `Titulo` VARCHAR(64) NOT NULL COMMENT 'Nombre del juego',
  `Annio` INT NOT NULL COMMENT 'Año de publicación',
  `ValoracionMedia` FLOAT NOT NULL DEFAULT 0 COMMENT 'Media de todas las valoraciones de los usuarios',
  `Descripcion` VARCHAR(512) NULL COMMENT 'Pequeña descripción del juego',
  `Genero_id` INT NOT NULL,
  `CalificacionEdad_id` INT NOT NULL,
  `Productora_id` INT NOT NULL,
  `Imagen` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Juego_Genero1_idx` (`Genero_id` ASC) ,
  INDEX `fk_Juego_CalificacionEdad1_idx` (`CalificacionEdad_id` ASC) ,
  INDEX `fk_Juego_Productora1_idx` (`Productora_id` ASC) ,
  CONSTRAINT `fk_Juego_Genero1`
    FOREIGN KEY (`Genero_id`)
    REFERENCES `gameCenter`.`Genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Juego_CalificacionEdad1`
    FOREIGN KEY (`CalificacionEdad_id`)
    REFERENCES `gameCenter`.`CalificacionEdad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Juego_Productora1`
    FOREIGN KEY (`Productora_id`)
    REFERENCES `gameCenter`.`Productora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabla con la información de los juegos';


-- -----------------------------------------------------
-- Table `gameCenter`.`Compannia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`Compannia` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`Compannia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(64) NOT NULL COMMENT 'Nombre de la compañia',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) )
ENGINE = InnoDB
COMMENT = 'Nombre de las compañias productoras de plataformas';


-- -----------------------------------------------------
-- Table `gameCenter`.`Plataforma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`Plataforma` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`Plataforma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(64) NOT NULL COMMENT 'Nombre de la plataforma',
  `Compannia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Plataforma_Compannia_idx` (`Compannia_id` ASC) ,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) ,
  CONSTRAINT `fk_Plataforma_Compannia`
    FOREIGN KEY (`Compannia_id`)
    REFERENCES `gameCenter`.`Compannia` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
COMMENT = 'Conjunto de plataformas en las que se pueden sacar los juegos\n';


-- -----------------------------------------------------
-- Table `gameCenter`.`PlataformaJuego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`PlataformaJuego` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`PlataformaJuego` (
  `Plataforma_id` INT NOT NULL,
  `Juego_id` INT NOT NULL,
  PRIMARY KEY (`Plataforma_id`, `Juego_id`),
  INDEX `fk_PlataformaJuego_Plataforma1_idx` (`Plataforma_id` ASC) ,
  INDEX `fk_PlataformaJuego_Juego1_idx` (`Juego_id` ASC) ,
  CONSTRAINT `fk_PlataformaJuego_Plataforma1`
    FOREIGN KEY (`Plataforma_id`)
    REFERENCES `gameCenter`.`Plataforma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlataformaJuego_Juego1`
    FOREIGN KEY (`Juego_id`)
    REFERENCES `gameCenter`.`Juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameCenter`.`CalificacionContenido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`CalificacionContenido` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`CalificacionContenido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(32) NOT NULL COMMENT 'Nombre de la calificación',
  `Imagen` VARCHAR(64) NOT NULL COMMENT 'Imagen de la calificación\n',
  `Descripcion` VARCHAR(128) NOT NULL COMMENT 'Descripción de la calificación\n',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) )
ENGINE = InnoDB
COMMENT = 'Posibles calificaciones de PEGI obtenidas por los juegos para las distintas edades';


-- -----------------------------------------------------
-- Table `gameCenter`.`JuegoCalificacionContenido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`JuegoCalificacionContenido` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`JuegoCalificacionContenido` (
  `Juego_id` INT NOT NULL,
  `CalificacionContenido_id` INT NOT NULL,
  INDEX `fk_JuegoCalificacionContenido_Juego1_idx` (`Juego_id` ASC) ,
  INDEX `fk_JuegoCalificacionContenido_CalificacionContenido1_idx` (`CalificacionContenido_id` ASC) ,
  PRIMARY KEY (`Juego_id`, `CalificacionContenido_id`),
  CONSTRAINT `fk_JuegoCalificacionContenido_Juego1`
    FOREIGN KEY (`Juego_id`)
    REFERENCES `gameCenter`.`Juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JuegoCalificacionContenido_CalificacionContenido1`
    FOREIGN KEY (`CalificacionContenido_id`)
    REFERENCES `gameCenter`.`CalificacionContenido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameCenter`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(64) NOT NULL COMMENT 'Nombre del susuario por el que es conocido',
  `Correo` VARCHAR(128) NOT NULL COMMENT 'Correo electronico de contacto',
  `Contrasennia` VARCHAR(128) NOT NULL COMMENT 'Contraseña del usuario ',
  `Annio` INT NOT NULL COMMENT 'Año de naciomiento con el que se calcula la edad',
  `Tipo` INT NOT NULL DEFAULT 0 COMMENT 'Tipos de usario:\n	- Usuario normal -> 0\n	- Usuario admin -> 1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) ,
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) )
ENGINE = InnoDB
COMMENT = 'Tabla con los datos del usuario';


-- -----------------------------------------------------
-- Table `gameCenter`.`Nick`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`Nick` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`Nick` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nick` VARCHAR(64) NULL COMMENT 'Pseudonimo del usuario',
  `Usuario_id` INT NOT NULL,
  `Juego_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Nick_Usuario1_idx` (`Usuario_id` ASC) ,
  INDEX `fk_Nick_Juego1_idx` (`Juego_id` ASC) ,
  CONSTRAINT `fk_Nick_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `gameCenter`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nick_Juego1`
    FOREIGN KEY (`Juego_id`)
    REFERENCES `gameCenter`.`Juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabla que relaciona los nobres utilizados en el juego por cada usuario';


-- -----------------------------------------------------
-- Table `gameCenter`.`Valoracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameCenter`.`Valoracion` ;

CREATE TABLE IF NOT EXISTS `gameCenter`.`Valoracion` (
  `Puntuacion` INT NOT NULL COMMENT 'Puntuacion otorgada por el usuario',
  `Comentario` VARCHAR(512) NULL COMMENT 'Comentario opcional del usuario',
  `Usuario_id` INT NOT NULL,
  `Juego_id` INT NOT NULL,
  `Fecha` DATE NOT NULL COMMENT 'Fecha en la que se publica la valoracion',
  `Hora` VARCHAR(9) NOT NULL COMMENT 'Hora en la que se publica la valoracion',
  PRIMARY KEY (`Usuario_id`, `Juego_id`),
  INDEX `fk_Valoracion_Usuario1_idx` (`Usuario_id` ASC) ,
  INDEX `fk_Valoracion_Juego1_idx` (`Juego_id` ASC) ,
  CONSTRAINT `fk_Valoracion_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `gameCenter`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Valoracion_Juego1`
    FOREIGN KEY (`Juego_id`)
    REFERENCES `gameCenter`.`Juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Comentarios y puntuaciones otorgadas por los usuarios';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
